spring.application.name=UserService

spring.datasource.url=jdbc:postgresql://db.bgnyaowlpoefrxerhlcn.supabase.co:5432/postgres
spring.datasource.username=stock_user-user
spring.datasource.password=*tAG-?7Zziygj&9
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
